// <auto-generated />

#nullable disable

using System;
using JsonApiBugReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace JsonApiBugReport.Migrations.SqlServer
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526093118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JsonApiBugReport.Data.PriceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PriceGroups");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowOrder")
                        .HasColumnType("bit");

                    b.Property<int>("ClassDiscriminator")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("Discriminator");

                    b.Property<Guid?>("CopyProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAddon")
                        .HasColumnType("bit")
                        .HasColumnName("IsAddon");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("bit")
                        .HasColumnName("IsBundle");

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("bit");

                    b.Property<int>("IsProductGroup")
                        .HasColumnType("int")
                        .HasColumnName("IsProductGroup");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PriceGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScreenshotLinkEnabled")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitGroupId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UnitGroupId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Products", t =>
                        {
                            t.HasTrigger("TR_tblProduct_Deleted");

                            t.HasTrigger("TR_tblProduct_Insert");
                        });

                    b.HasDiscriminator<int>("ClassDiscriminator");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("JsonApiBugReport.Data.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mnemonic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(32, 10)
                        .HasColumnType("decimal(32,10)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.UnitGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("UnitGroups");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApiUser")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.CommonProduct", b =>
                {
                    b.HasBaseType("JsonApiBugReport.Data.ProductBase");

                    b.Property<int>("IsTaxable")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("PriceGroupId");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductGroup", b =>
                {
                    b.HasBaseType("JsonApiBugReport.Data.ProductBase");

                    b.Property<int?>("IncludeAllProducts")
                        .HasColumnType("int");

                    b.HasIndex("CopyProductId");

                    b.HasIndex("PriceGroupId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductBundle", b =>
                {
                    b.HasBaseType("JsonApiBugReport.Data.CommonProduct");

                    b.HasIndex("CopyProductId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("JsonApiBugReport.Data.StandaloneProduct", b =>
                {
                    b.HasBaseType("JsonApiBugReport.Data.CommonProduct");

                    b.Property<bool>("AllowsCustomEndDate")
                        .HasColumnType("bit");

                    b.Property<int?>("TrialDuration")
                        .HasColumnType("int");

                    b.Property<int?>("TrialNo")
                        .HasColumnType("int");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.Product", b =>
                {
                    b.HasBaseType("JsonApiBugReport.Data.StandaloneProduct");

                    b.Property<bool?>("SupportsMonthlyBillingFrequency")
                        .HasColumnType("bit");

                    b.HasIndex("CopyProductId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductAddon", b =>
                {
                    b.HasBaseType("JsonApiBugReport.Data.StandaloneProduct");

                    b.HasIndex("CopyProductId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("JsonApiBugReport.Data.PriceGroup", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JsonApiBugReport.Data.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductBase", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JsonApiBugReport.Data.UnitGroup", "UnitGroup")
                        .WithMany()
                        .HasForeignKey("UnitGroupId");

                    b.HasOne("JsonApiBugReport.Data.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UnitGroup");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.Unit", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.UnitGroup", "Parent")
                        .WithMany("Units")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.UnitGroup", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JsonApiBugReport.Data.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.CommonProduct", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.PriceGroup", "PriceGroup")
                        .WithMany("Products")
                        .HasForeignKey("PriceGroupId");

                    b.HasOne("JsonApiBugReport.Data.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId");

                    b.Navigation("PriceGroup");

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductGroup", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.ProductGroup", "CopyOf")
                        .WithMany()
                        .HasForeignKey("CopyProductId");

                    b.HasOne("JsonApiBugReport.Data.PriceGroup", "PriceGroup")
                        .WithMany()
                        .HasForeignKey("PriceGroupId");

                    b.Navigation("CopyOf");

                    b.Navigation("PriceGroup");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductBundle", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.ProductBundle", "CopyOf")
                        .WithMany()
                        .HasForeignKey("CopyProductId");

                    b.Navigation("CopyOf");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.Product", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.Product", "CopyOf")
                        .WithMany()
                        .HasForeignKey("CopyProductId");

                    b.Navigation("CopyOf");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductAddon", b =>
                {
                    b.HasOne("JsonApiBugReport.Data.ProductAddon", "CopyOf")
                        .WithMany()
                        .HasForeignKey("CopyProductId");

                    b.Navigation("CopyOf");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.PriceGroup", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.UnitGroup", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("JsonApiBugReport.Data.ProductGroup", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
